# -*- coding: utf-8 -*-
"""Grad_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/reemissasaleh/grad-project.3b261b64-bb29-4338-b5d9-7ce1e7e81126.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260922/auto/storage/goog4_request%26X-Goog-Date%3D20260922T201138Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4b0a2912d333eeeed6783dace79334e3129434911d0564f643a3e688c3f52f4ec3ab60426b0106e76f14672ee11b8fea51d3c684435650ddcf9702a0f758c43183848705f98264f1f801ee5703ddb875ab9fe3082bb96bb9f6b92dddd29417ca416a018cd32f82b154a34f4b63bcf4fa8db38b08127457c97874ef93d4ce7dd250807ec121e493d7ce00858021bf76479972cc9cedcc95a2828e7fa23a9e66bd1f685b459cace265672d90991879e3705595b4a1cb72326af417f21141e285cbe090cfd6a4598e6589cd605cd5a750b318bc91af1a2cca1cb46abeb27cc17d4d9b4cd96dc083ed4de93a5119f4304742bcc6bee9bb2c9c2a0057a1129918a7d5
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

reemissasaleh_grad_project_path = kagglehub.notebook_output_download('reemissasaleh/grad-project')

print('Data source import complete.')

!pip install roboflow ultralytics

from roboflow import Roboflow

rf = Roboflow(api_key="x19TylcRGNSRhd1GEwbe")

project = rf.workspace("solar-panel-detection-pz2ap").project("crack-solar-panel")
dataset = project.version(1).download("yolov8")

project2 = rf.workspace("solarvision-gwljt").project("solar-panel-fault-detection")
dataset2 = project2.version(2).download("yolov8")

from roboflow import Roboflow

# Dataset 2
project2 = rf.workspace(
    "solarvision-gwljt"
).project(
    "solar-panel-fault-detection"
)

dataset2 = project2.version(2).download("yolov8")

print("✅ Dataset 2 downloaded successfully")
print("Location:", dataset2.location)

from roboflow import Roboflow
from pathlib import Path
import shutil

# ============================================================
# DOWNLOAD DATASET 2 AGAIN
# ============================================================

rf = Roboflow(api_key="x19TylcRGNSRhd1GEwbe")

project2 = rf.workspace(
    "solarvision-gwljt"
).project(
    "solar-panel-fault-detection"
)

print("Downloading Dataset 2...")

dataset2 = project2.version(2).download(
    "yolov8",
    location="/content/solar_fault_dataset"
)

print("\n" + "=" * 60)
print("DOWNLOAD RESULT")
print("=" * 60)

print("Location:", dataset2.location)

# فحص الملفات
dataset_path = Path("/content/solar_fault_dataset")

print("\nDataset contents:")

if dataset_path.exists():
    for item in dataset_path.iterdir():
        print("📁" if item.is_dir() else "📄", item.name)

    yaml_path = dataset_path / "data.yaml"

    print("\nData.yaml exists:", yaml_path.exists())

else:
    print("❌ Dataset directory was not created")

import yaml
from pathlib import Path

# ============================================================
# DATASET 2 - CLASS VERIFICATION
# ============================================================

dataset2_path = Path("/content/solar_fault_dataset")
yaml_path = dataset2_path / "data.yaml"

print("=" * 60)
print("DATASET 2 CLASS VERIFICATION")
print("=" * 60)

with open(yaml_path, "r") as f:
    data2 = yaml.safe_load(f)

print("Classes:", data2["names"])
print("Number of classes:", data2["nc"])

print("\n" + "=" * 60)
print("DATASET 2 STRUCTURE")
print("=" * 60)

for folder in ["train", "valid", "test"]:
    folder_path = dataset2_path / folder

    images_path = folder_path / "images"
    labels_path = folder_path / "labels"

    print(f"\n{folder.upper()}:")
    print("  Images:", len(list(images_path.glob("*"))) if images_path.exists() else 0)
    print("  Labels:", len(list(labels_path.glob("*.txt"))) if labels_path.exists() else 0)

from pathlib import Path
from collections import Counter

dataset2_path = Path("/content/solar_fault_dataset")

print("=" * 60)
print("DATASET 2 LABEL DISTRIBUTION")
print("=" * 60)

class_counts = Counter()

for split in ["train", "valid", "test"]:

    labels_dir = dataset2_path / split / "labels"

    split_counts = Counter()

    for label_file in labels_dir.glob("*.txt"):

        with open(label_file, "r") as f:

            for line in f:
                line = line.strip()

                if not line:
                    continue

                class_id = int(line.split()[0])

                class_counts[class_id] += 1
                split_counts[class_id] += 1

    print(f"\n{split.upper()}:")

    for class_id in sorted(split_counts):
        print(
            f"Class {class_id}: "
            f"{split_counts[class_id]} objects"
        )


print("\n" + "=" * 60)
print("TOTAL")
print("=" * 60)

class_names = [
    "BakimGereken",
    "Cracked",
    "Dirty",
    "Good",
    "Saglam"
]

for class_id in sorted(class_counts):

    print(
        f"Class {class_id} "
        f"({class_names[class_id]}): "
        f"{class_counts[class_id]} objects"
    )

import os

# Dataset الأول
print("=== Dataset 1: Crack Solar Panel ===")
for folder in os.listdir("Crack-Solar-Panel-1"):
    print(folder)

print("\n=== Dataset 2: Solar Panel Fault Detection ===")
for folder in os.listdir("Solar-Panel-Fault-Detection-2"):
    print(folder)

import yaml
from pathlib import Path

print("=" * 60)
print("CHECKING DATASET FILES")
print("=" * 60)

# ============================================================
# Dataset 1
# ============================================================

dataset1_yaml = Path("/content/Crack-Solar-Panel-1/data.yaml")

print("\n=== Dataset 1 ===")

if dataset1_yaml.exists():

    with open(dataset1_yaml, "r") as f:
        data1 = yaml.safe_load(f)

    print("Path:", dataset1_yaml)
    print("Classes:", data1.get("names"))
    print("Number of classes:", data1.get("nc"))

else:
    print("❌ Dataset 1 data.yaml NOT FOUND")
    print("Expected:", dataset1_yaml)


# ============================================================
# Dataset 2
# ============================================================

dataset2_yaml = Path("/content/Solar-Panel-Fault-Detection-2/data.yaml")

print("\n=== Dataset 2 ===")

if dataset2_yaml.exists():

    with open(dataset2_yaml, "r") as f:
        data2 = yaml.safe_load(f)

    print("Path:", dataset2_yaml)
    print("Classes:", data2.get("names"))
    print("Number of classes:", data2.get("nc"))

else:
    print("❌ Dataset 2 data.yaml NOT FOUND")
    print("Expected:", dataset2_yaml)


# ============================================================
# Summary
# ============================================================

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)

if dataset1_yaml.exists():
    print("Dataset 1:", data1["names"])

if dataset2_yaml.exists():
    print("Dataset 2:", data2["names"])

import os
import shutil

# تحديد الفئات التي نريدها من Dataset 2
# المفتاح = الرقم القديم، القيمة = الاسم الجديد
class_mapping = {
    0: "Physical_Damage",  # BakimGereken
    1: "Crack",            # Cracked
    2: None,               # Dirty - لا نريده
    3: "Good",             # Good
    4: "Good",             # Saglam = Good أيضاً
}

# الفئات النهائية وأرقامها
final_classes = ["Crack", "Good", "Physical_Damage"]

# إنشاء مجلدات الدمج
for split in ["train", "valid", "test"]:
    os.makedirs(f"merged/{split}/images", exist_ok=True)
    os.makedirs(f"merged/{split}/labels", exist_ok=True)

print("✅ تم إنشاء مجلدات الدمج")

for split in ["train", "valid", "test"]:
    # مسار الصور والـ labels
    img_src = f"Crack-Solar-Panel-1/{split}/images"
    lbl_src = f"Crack-Solar-Panel-1/{split}/labels"

    # نسخ الصور
    for img in os.listdir(img_src):
        shutil.copy(f"{img_src}/{img}", f"merged/{split}/images/ds1_{img}")

    # نسخ الـ labels
    for lbl in os.listdir(lbl_src):
        shutil.copy(f"{lbl_src}/{lbl}", f"merged/{split}/labels/ds1_{lbl}")

print("✅ تم نسخ Dataset 1 بنجاح")

# نسخ Dataset 2 مع تحويل الفئات
for split in ["train", "valid", "test"]:
    img_src = f"/content/solar_fault_dataset/{split}/images"
    lbl_src = f"/content/solar_fault_dataset/{split}/labels"

    # نسخ الصور
    for img in os.listdir(img_src):
        shutil.copy(f"{img_src}/{img}", f"merged/{split}/images/ds2_{img}")

    # تحويل الـ labels
    for lbl in os.listdir(lbl_src):
        with open(f"{lbl_src}/{lbl}", "r") as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            parts = line.strip().split()
            old_class = int(parts[0])
            new_class_name = class_mapping[old_class]

            # تجاهل Dirty
            if new_class_name is None:
                continue

            # تحويل الاسم للرقم الجديد
            new_class_num = final_classes.index(new_class_name)
            parts[0] = str(new_class_num)
            new_lines.append(" ".join(parts) + "\n")

        # حفظ الـ label الجديد
        if new_lines:
            with open(f"merged/{split}/labels/ds2_{lbl}", "w") as f:
                f.writelines(new_lines)

print("✅ تم نسخ Dataset 2 مع تحويل الفئات بنجاح")

from pathlib import Path

# ============================================================
# REMOVE IMAGES WITHOUT LABELS
# ============================================================

merged_path = Path("/kaggle/working/merged")

print("=" * 70)
print("REMOVING IMAGES WITHOUT LABELS")
print("=" * 70)

total_removed = 0

for split in ["train", "valid", "test"]:

    images_path = merged_path / split / "images"
    labels_path = merged_path / split / "labels"

    removed = 0

    for image_file in images_path.iterdir():

        label_file = labels_path / f"{image_file.stem}.txt"

        if not label_file.exists():

            image_file.unlink()

            removed += 1
            total_removed += 1

    print(f"{split.upper()}: Removed {removed} images")

print("\n" + "=" * 70)
print(f"TOTAL REMOVED: {total_removed}")
print("=" * 70)

import os
from pathlib import Path
from collections import Counter

# ============================================================
# MERGED DATASET VERIFICATION
# ============================================================

merged_path = Path("/kaggle/working/merged")

print("=" * 70)
print("MERGED DATASET VERIFICATION")
print("=" * 70)

total_images = 0
total_labels = 0

for split in ["train", "valid", "test"]:

    images_path = merged_path / split / "images"
    labels_path = merged_path / split / "labels"

    images = list(images_path.iterdir())
    labels = list(labels_path.glob("*.txt"))

    image_names = {x.stem for x in images}
    label_names = {x.stem for x in labels}

    missing_labels = image_names - label_names
    missing_images = label_names - image_names

    print("\n" + "=" * 50)
    print(split.upper())
    print("=" * 50)

    print("Images :", len(images))
    print("Labels :", len(labels))
    print("Images without labels :", len(missing_labels))
    print("Labels without images :", len(missing_images))

    if len(missing_labels) == 0 and len(missing_images) == 0:
        print("✅ Images and labels are correctly matched")
    else:
        print("⚠️ There are mismatches")

    total_images += len(images)
    total_labels += len(labels)

print("\n" + "=" * 70)
print("TOTAL DATASET")
print("=" * 70)

print("Total Images :", total_images)
print("Total Labels :", total_labels)


# ============================================================
# LABEL VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("LABEL VALIDATION")
print("=" * 70)

class_counts = Counter()
empty_labels = 0
invalid_labels = 0

for split in ["train", "valid", "test"]:

    labels_path = merged_path / split / "labels"

    for label_file in labels_path.glob("*.txt"):

        with open(label_file, "r") as f:
            lines = f.readlines()

        if len(lines) == 0:
            empty_labels += 1
            continue

        for line in lines:

            parts = line.strip().split()

            if len(parts) != 5:
                invalid_labels += 1
                continue

            try:
                class_id = int(parts[0])
                x, y, w, h = map(float, parts[1:])

                # يجب أن تكون الـclasses من 0 إلى 2
                if class_id not in [0, 1, 2]:
                    invalid_labels += 1
                    continue

                # YOLO coordinates يجب أن تكون بين 0 و 1
                if not all(0 <= value <= 1 for value in [x, y, w, h]):
                    invalid_labels += 1
                    continue

                # width و height يجب أن تكون أكبر من صفر
                if w <= 0 or h <= 0:
                    invalid_labels += 1
                    continue

                class_counts[class_id] += 1

            except:
                invalid_labels += 1


print("\nClasses found:")

class_names = {
    0: "Crack",
    1: "Good",
    2: "Physical_Damage"
}

for class_id in [0, 1, 2]:

    print(
        f"Class {class_id} ({class_names[class_id]}): "
        f"{class_counts[class_id]} objects"
    )

print("\nEmpty label files   :", empty_labels)
print("Invalid label entries:", invalid_labels)

if empty_labels == 0 and invalid_labels == 0:
    print("\n✅ All label entries passed validation")
else:
    print("\n⚠️ Some label problems were detected")

import yaml

data = {
    'train': 'merged/train/images',
    'val': 'merged/valid/images',
    'test': 'merged/test/images',
    'nc': 3,
    'names': ['Crack', 'Good', 'Physical_Damage']
}

with open("merged/data.yaml", "w") as f:
    yaml.dump(data, f, default_flow_style=False)

print("✅ تم إنشاء data.yaml بنجاح")

import yaml

yaml_path = "/kaggle/working/merged/data.yaml"

data = {
    "path": "/kaggle/working/merged",
    "train": "train/images",
    "val": "valid/images",
    "test": "test/images",
    "nc": 3,
    "names": [
        "Crack",
        "Good",
        "Physical_Damage"
    ]
}

with open(yaml_path, "w") as f:
    yaml.dump(data, f, sort_keys=False)

print("✅ data.yaml updated successfully")

with open(yaml_path, "r") as f:
    print(f.read())

# ============================================================
# YOLOv8 - BASELINE TRAINING
# ============================================================

!pip install ultralytics -q

from ultralytics import YOLO
import os
import yaml

# ============================================================
# 1. التأكد من Dataset
# ============================================================

dataset_path = "/kaggle/working/merged"
yaml_path = os.path.join(dataset_path, "data.yaml")

print("=" * 60)
print("DATASET CONFIGURATION")
print("=" * 60)

if not os.path.exists(yaml_path):
    raise FileNotFoundError(
        f"data.yaml not found at: {yaml_path}"
    )

with open(yaml_path, "r") as f:
    data_config = yaml.safe_load(f)

print("\nDataset YAML:")
print(data_config)

print("\nClasses:")
for i, name in enumerate(data_config["names"]):
    print(f"Class {i}: {name}")

print(f"\nNumber of classes: {data_config['nc']}")

# ============================================================
# 2. تحميل YOLOv8
# ============================================================

model = YOLO("yolov8n.pt")

print("\n✅ YOLOv8 model loaded successfully")

for split in ["train", "valid", "test"]:
    imgs_dir = f"merged/{split}/images"
    lbls_dir = f"merged/{split}/labels"

    # نأخذ أسماء الصور بدون امتداد آخر نقطة فقط
    images = set([f.rsplit(".", 1)[0] for f in os.listdir(imgs_dir)])
    labels = set([f.rsplit(".", 1)[0] for f in os.listdir(lbls_dir)])

    no_label = images - labels

    for img_name in no_label:
        for ext in [".jpg", ".jpeg", ".png"]:
            img_path = f"{imgs_dir}/{img_name}{ext}"
            if os.path.exists(img_path):
                os.remove(img_path)
                break

    print(f"✅ {split}: تم حذف {len(no_label)} صورة بدون label")

for split in ["train", "valid", "test"]:
    images = len(os.listdir(f"merged/{split}/images"))
    labels = len(os.listdir(f"merged/{split}/labels"))
    print(f"{split}: {images} صورة, {labels} label")

# ============================================================
# PREPROCESSING - FULL DATASET
# ============================================================

!pip install opencv-python albumentations numpy pandas matplotlib pillow -q

import cv2
import numpy as np
import albumentations as A
from albumentations.pytorch import ToTensorV2
import os
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


# ============================================================
# Dataset Paths
# ============================================================

dataset_path = Path("/kaggle/working/merged")
output_path = Path("/kaggle/working/preprocessed")

splits = ["train", "valid", "test"]


# ============================================================
# 1- CLAHE
# ============================================================

def apply_clahe(image):

    lab = cv2.cvtColor(image, cv2.COLOR_RGB2LAB)

    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8, 8)
    )

    l_clahe = clahe.apply(l)

    lab_clahe = cv2.merge([
        l_clahe,
        a,
        b
    ])

    image_clahe = cv2.cvtColor(
        lab_clahe,
        cv2.COLOR_LAB2RGB
    )

    return image_clahe


# ============================================================
# 2- Gaussian Blur
# ============================================================

def apply_gaussian_blur(image, kernel_size=3):

    blurred = cv2.GaussianBlur(
        image,
        (kernel_size, kernel_size),
        0
    )

    return blurred


# ============================================================
# 3- Letterbox Resize
# ============================================================

def resize_with_padding(image, target_size=416):

    h, w = image.shape[:2]

    scale = target_size / max(h, w)

    new_h = int(h * scale)
    new_w = int(w * scale)

    resized = cv2.resize(
        image,
        (new_w, new_h),
        interpolation=cv2.INTER_LINEAR
    )

    top = (target_size - new_h) // 2
    bottom = target_size - new_h - top

    left = (target_size - new_w) // 2
    right = target_size - new_w - left

    padded = cv2.copyMakeBorder(
        resized,
        top,
        bottom,
        left,
        right,
        cv2.BORDER_CONSTANT,
        value=(114, 114, 114)
    )

    return padded, scale, left, top


# ============================================================
# 4- Normalization
# ============================================================

def normalize_image(image, method='imagenet'):

    if method == 'simple':

        normalized = (
            image.astype(np.float32) / 255.0
        )

    elif method == 'imagenet':

        image_float = (
            image.astype(np.float32) / 255.0
        )

        imagenet_mean = np.array([
            0.485,
            0.456,
            0.406
        ])

        imagenet_std = np.array([
            0.229,
            0.224,
            0.225
        ])

        normalized = (
            image_float - imagenet_mean
        ) / imagenet_std

    return normalized


# ============================================================
# YOLO Label Transformation
# ============================================================

def transform_yolo_labels(
    label_path,
    output_label_path,
    original_width,
    original_height,
    scale,
    pad_x,
    pad_y,
    target_size=416
):

    if not label_path.exists():
        return

    new_labels = []

    with open(label_path, "r") as f:

        for line in f:

            parts = line.strip().split()

            if len(parts) != 5:
                continue

            class_id = parts[0]

            x_center = float(parts[1])
            y_center = float(parts[2])
            box_width = float(parts[3])
            box_height = float(parts[4])

            # YOLO normalized coordinates
            x_center_pixel = x_center * original_width
            y_center_pixel = y_center * original_height

            box_width_pixel = box_width * original_width
            box_height_pixel = box_height * original_height

            # Resize
            x_center_pixel *= scale
            y_center_pixel *= scale

            box_width_pixel *= scale
            box_height_pixel *= scale

            # Padding
            x_center_pixel += pad_x
            y_center_pixel += pad_y

            # Convert back to YOLO normalized coordinates
            new_x_center = x_center_pixel / target_size
            new_y_center = y_center_pixel / target_size

            new_width = box_width_pixel / target_size
            new_height = box_height_pixel / target_size

            new_labels.append(
                f"{class_id} "
                f"{new_x_center:.6f} "
                f"{new_y_center:.6f} "
                f"{new_width:.6f} "
                f"{new_height:.6f}\n"
            )

    with open(output_label_path, "w") as f:
        f.writelines(new_labels)


# ============================================================
# Process Entire Dataset
# ============================================================

total_images = 0

for split in splits:

    print("\n" + "=" * 60)
    print(f"PROCESSING: {split.upper()}")
    print("=" * 60)

    input_images = dataset_path / split / "images"
    input_labels = dataset_path / split / "labels"

    output_images = output_path / split / "images"
    output_labels = output_path / split / "labels"

    output_images.mkdir(
        parents=True,
        exist_ok=True
    )

    output_labels.mkdir(
        parents=True,
        exist_ok=True
    )

    image_files = list(input_images.glob("*"))

    processed_count = 0

    for image_path in image_files:

        if image_path.suffix.lower() not in [
            ".jpg",
            ".jpeg",
            ".png",
            ".bmp"
        ]:
            continue

        # ----------------------------------------------------
        # Load Image
        # ----------------------------------------------------

        image = cv2.imread(str(image_path))

        if image is None:
            print(f"⚠️ Could not read: {image_path.name}")
            continue

        image = cv2.cvtColor(
            image,
            cv2.COLOR_BGR2RGB
        )

        original_height, original_width = image.shape[:2]


        # ----------------------------------------------------
        # 1- CLAHE
        # ----------------------------------------------------

        image_clahe = apply_clahe(image)


        # ----------------------------------------------------
        # 2- Gaussian Blur
        # ----------------------------------------------------

        # النسخة مع Blur
        with_blur = apply_gaussian_blur(
            image_clahe,
            kernel_size=3
        )

        # ----------------------------------------------------
        # 3- Letterbox Resize
        # ----------------------------------------------------

        resized_image, scale, pad_x, pad_y = \
            resize_with_padding(
                with_blur,
                target_size=416
            )


        # ----------------------------------------------------
        # 4- Normalization
        # ----------------------------------------------------

        normalized_image = normalize_image(
            resized_image,
            method='imagenet'
        )


        # ----------------------------------------------------
        # Convert back to uint8 for saving
        # ----------------------------------------------------

        imagenet_mean = np.array([
            0.485,
            0.456,
            0.406
        ])

        imagenet_std = np.array([
            0.229,
            0.224,
            0.225
        ])

        image_to_save = (
            normalized_image * imagenet_std
            + imagenet_mean
        )

        image_to_save = np.clip(
            image_to_save * 255.0,
            0,
            255
        ).astype(np.uint8)


        # RGB → BGR
        image_to_save = cv2.cvtColor(
            image_to_save,
            cv2.COLOR_RGB2BGR
        )


        # ----------------------------------------------------
        # Save Image
        # ----------------------------------------------------

        output_image_path = (
            output_images / image_path.name
        )

        cv2.imwrite(
            str(output_image_path),
            image_to_save
        )


        # ----------------------------------------------------
        # Transform and Save YOLO Labels
        # ----------------------------------------------------

        label_path = (
            input_labels /
            f"{image_path.stem}.txt"
        )

        output_label_path = (
            output_labels /
            f"{image_path.stem}.txt"
        )

        transform_yolo_labels(
            label_path,
            output_label_path,
            original_width,
            original_height,
            scale,
            pad_x,
            pad_y,
            target_size=416
        )


        processed_count += 1
        total_images += 1


    print(
        f"✅ Processed images: {processed_count}"
    )


# ============================================================
# Final Result
# ============================================================

print("\n" + "=" * 60)
print("PREPROCESSING COMPLETED")
print("=" * 60)

print(f"Total processed images: {total_images}")
print(f"Output dataset: {output_path}")

from pathlib import Path
import os

preprocessed_path = Path("/kaggle/working/preprocessed")

print("=== Checking Preprocessed Dataset ===")

if preprocessed_path.exists():
    print("✅ Preprocessed dataset exists")

    for split in ["train", "valid", "test"]:
        images_path = preprocessed_path / split / "images"
        labels_path = preprocessed_path / split / "labels"

        image_count = len(list(images_path.glob("*"))) if images_path.exists() else 0
        label_count = len(list(labels_path.glob("*.txt"))) if labels_path.exists() else 0

        print(f"\n{split.upper()}:")
        print(f"Images: {image_count}")
        print(f"Labels: {label_count}")
else:
    print("❌ Preprocessed dataset does not exist")

import yaml
from pathlib import Path

# ============================================================
# Create data.yaml for PREPROCESSED dataset
# ============================================================

preprocessed_path = Path("/kaggle/working/preprocessed")

yaml_path = preprocessed_path / "data.yaml"

data = {
    "path": str(preprocessed_path),
    "train": "train/images",
    "val": "valid/images",
    "test": "test/images",
    "nc": 3,
    "names": [
        "Crack",
        "Good",
        "Physical_Damage"
    ]
}

with open(yaml_path, "w") as f:
    yaml.dump(data, f, sort_keys=False)

print("✅ Preprocessed data.yaml created successfully")
print(f"📁 Path: {yaml_path}")

print("\n=== data.yaml ===")
with open(yaml_path, "r") as f:
    print(f.read())

from ultralytics import YOLO
from pathlib import Path
import shutil

# ============================================================
# YOLOv8 TRAINING - PREPROCESSED DATASET
# ============================================================

data_yaml = "/kaggle/working/preprocessed/data.yaml"

run_name = "yolov8_preprocessed"

# Training output
project_dir = Path("/kaggle/working/runs")
run_dir = project_dir / run_name
weights_dir = run_dir / "weights"

# External model directory
export_dir = Path("/kaggle/working/model")
export_dir.mkdir(parents=True, exist_ok=True)

print("=" * 60)
print("STARTING YOLOv8 TRAINING")
print("=" * 60)

print(f"Dataset    : {data_yaml}")
print(f"Model      : YOLOv8n")
print(f"Epochs     : 50")
print(f"Batch      : 16")
print(f"Image Size : 416")

# ============================================================
# LOAD PRETRAINED YOLOv8n
# ============================================================

model = YOLO("yolov8n.pt")

print("✅ YOLOv8n loaded successfully")

# ============================================================
# TRAIN
# ============================================================

results = model.train(
    data=data_yaml,

    # Model training
    epochs=50,
    imgsz=416,
    batch=16,

    # Pretrained model
    pretrained=True,

    # Validation
    val=True,

    # Early stopping
    patience=10,

    # Data augmentation
    augment=True,
    mosaic=1.0,
    fliplr=0.5,

    # Reproducibility
    seed=0,
    deterministic=True,

    # Saving
    save=True,
    save_period=1,

    # Output
    project=str(project_dir),
    name=run_name,
    exist_ok=True,

    # Logging / plots
    plots=True,
    verbose=True
)

# ============================================================
# TRAINING FINISHED
# ============================================================

print("\n" + "=" * 60)
print("TRAINING FINISHED")
print("=" * 60)

print(f"Run directory: {run_dir}")

# ============================================================
# CHECK TRAINING WEIGHTS
# ============================================================

print("\n=== Checking Training Weights ===")

best_pt = weights_dir / "best.pt"
last_pt = weights_dir / "last.pt"

if best_pt.exists():
    print(f"✅ best.pt found: {best_pt}")
    print(f"   Size: {best_pt.stat().st_size / (1024**2):.2f} MB")
else:
    print("❌ best.pt NOT FOUND")

if last_pt.exists():
    print(f"✅ last.pt found: {last_pt}")
    print(f"   Size: {last_pt.stat().st_size / (1024**2):.2f} MB")
else:
    print("❌ last.pt NOT FOUND")

# ============================================================
# COPY BEST MODEL TO EXTERNAL MODEL DIRECTORY
# ============================================================

if best_pt.exists():

    external_best = export_dir / "best.pt"

    shutil.copy2(
        best_pt,
        external_best
    )

    print("\n" + "=" * 60)
    print("MODEL EXPORTED SUCCESSFULLY")
    print("=" * 60)

    print(f"✅ External model:")
    print(f"   {external_best}")

    print(
        f"   Size: "
        f"{external_best.stat().st_size / (1024**2):.2f} MB"
    )

else:

    print("\n❌ Cannot export model because best.pt was not found.")

# ============================================================
# LIST FINAL MODEL DIRECTORY
# ============================================================

print("\n=== Final Model Directory ===")

if export_dir.exists():

    for file in export_dir.iterdir():
        print(f"✅ {file}")

# ============================================================
# TEST EXPORTED MODEL
# ============================================================

if (export_dir / "best.pt").exists():

    print("\n=== Testing Exported Model ===")

    test_model = YOLO(
        str(export_dir / "best.pt")
    )

    print("✅ best.pt loaded successfully")
    print(f"Classes: {test_model.names}")

else:

    print("❌ Exported model does not exist.")

from pathlib import Path

print("=== Searching for best.pt ===")

best_files = list(
    Path("/kaggle/working").rglob("best.pt")
)

for f in best_files:
    print("✅", f)

if not best_files:
    print("❌ best.pt not found")

from IPython.display import FileLink

model_path = "/kaggle/working/model/best.pt"

FileLink(model_path)